#!/bin/bash
source config.sh

echo "Starting 2. Genome survey using kmer distribution generated by the Illumina reads with KMC (v3.2.1) and GenomeScope (V2.0)"
ATA_DIR="data/merge"
GENOMESCOPE_SCRIPT="genomescope2.0/genomescope.R"

# Create output directory and move into it
MAIN_OUTPUT_DIR="genomescope_analysis"
mkdir -p "${MAIN_OUTPUT_DIR}"
cd "${MAIN_OUTPUT_DIR}"

# Loop through k-mer sizes and samples
for i in 18 21 24 27 30 33 36 39 42 45 48 51 54; do 
  for n in F4 M4; do

    KMC_DB="merge_${n}_k${i}_kmc"
    HISTO_FILE="merge_${n}_${i}.histo"
    OUTPUT_DIR="genomescope_output_${n}_${i}"
    
    if [[ -s "$HISTO_FILE" ]]; then
      echo "$HISTO_FILE exists and is non-empty, skipping..."
      continue
    fi

    echo "Counting k-mers for $n at k=$i..."
    if [[ ! -s "$KMC_DB.1" ]]; then
      pixi run kmc \
      -k${i} \
      -t36 \
      -m80 \
      -ci3 \
      -cs10000 \
      -f \
      "${DATA_DIR}/merge_${n}_R1.fastq.gz" \
      "$KMC_DB.1" \
      genomescope_analysis/tmp_kmc_dir
    fi
    if [[ ! -s "$KMC_DB.2" ]]; then
       pixi run kmc \
      -k${i} \
      -t36 \
      -m80 \
      -ci3 \
      -cs10000 \
      -f \
      "${DATA_DIR}/merge_${n}_R2.fastq.gz" \
      "$KMC_DB.2" \
      genomescope_analysis/tmp_kmc_dir
    fi
   
    pixi run kmc_tools simple $KMC_DB.1 $KMC_DB.2 union $KMC_DB.merged

    echo "Generating histogram for $n at k=$i..."
   pixi run kmc_tools transform "./$KMC_DB.merged" histogram "$HISTO_FILE"

    echo "Running GenomeScope for $n at k=$i..."
   pixi run Rscript "$GENOMESCOPE_SCRIPT" \
      -i "$HISTO_FILE" \
      -o "$OUTPUT_DIR" \
      -k $i

  done 
done
